"""Generate data/themes/*.qss from one template + per-theme palettes.
Run: python scripts/gen_themes.py"""
from pathlib import Path

TEMPLATE = """\
/* {NAME} theme — generated by scripts/gen_themes.py; edit there, not here */
* {{ font-family: "Segoe UI", "Microsoft YaHei", "PingFang SC", sans-serif; }}
QWidget {{ background: {BG}; color: {TEXT}; font-size: 14px; }}
QMainWindow, QDialog {{ background: {BG}; }}
QLabel {{ background: transparent; }}

QToolBar {{ background: {TOOLBAR}; border: none; border-bottom: 1px solid {BORDER};
           spacing: 3px; padding: 6px 8px; }}
QToolBar::separator {{ background: {BORDER}; width: 1px; margin: 5px 6px; }}

/* left navigation sidebar */
QToolBar#sidebar {{ background: {TOOLBAR}; border: none; border-right: 1px solid {BORDER};
    border-bottom: none; spacing: 4px; padding: 14px 10px; min-width: 138px; }}
QToolBar#sidebar QToolButton {{ text-align: left; padding: 10px 14px; min-width: 110px;
    border-radius: 10px; font-size: 14px; }}
QToolBar#sidebar QToolButton:hover {{ background: {HOVER}; }}
QToolBar#sidebar QToolButton:checked {{ background: {SEL}; color: {ACCENT}; font-weight: 600; }}

QToolButton {{ background: transparent; color: {TEXT}; border: none;
              padding: 6px 10px; border-radius: 8px; }}
QToolButton:hover {{ background: {HOVER}; }}
QToolButton:pressed {{ background: {SEL}; }}
QToolButton:checked {{ background: {SEL}; }}
QToolButton::menu-indicator {{ image: none; }}

QPushButton {{ background: {ACCENT}; color: {ON_ACCENT}; border: none;
              padding: 7px 16px; border-radius: 8px; font-weight: 600; }}
QPushButton:hover {{ background: {ACCENT_H}; }}
QPushButton:pressed {{ background: {ACCENT_P}; }}
QPushButton:disabled {{ background: {DISABLED}; color: {MUTED}; }}

QLineEdit, QSpinBox, QComboBox, QPlainTextEdit, QTextEdit {{
    background: {SURFACE}; color: {TEXT}; border: 1px solid {BORDER};
    border-radius: 8px; padding: 6px 9px; selection-background-color: {ACCENT};
    selection-color: {ON_ACCENT}; }}
QLineEdit:focus, QSpinBox:focus, QComboBox:focus, QPlainTextEdit:focus {{
    border: 1px solid {ACCENT}; }}
QComboBox:hover {{ border: 1px solid {ACCENT}; }}
QComboBox::drop-down {{ border: none; width: 22px; }}
QComboBox QAbstractItemView {{ background: {SURFACE}; color: {TEXT};
    border: 1px solid {BORDER}; border-radius: 8px; outline: none;
    selection-background-color: {HOVER}; selection-color: {TEXT}; padding: 4px; }}
QSpinBox::up-button, QSpinBox::down-button {{ width: 16px; border: none; background: {HOVER}; }}

QMenu {{ background: {SURFACE}; color: {TEXT}; border: 1px solid {BORDER};
         border-radius: 10px; padding: 6px; }}
QMenu::item {{ padding: 6px 22px 6px 14px; border-radius: 6px; }}
QMenu::item:selected {{ background: {HOVER}; }}
QMenu::separator {{ height: 1px; background: {BORDER}; margin: 5px 8px; }}

QFrame {{ background: {SURFACE}; border: 1px solid {BORDER}; border-radius: 12px; }}
QGroupBox {{ background: {SURFACE}; border: 1px solid {BORDER}; border-radius: 12px;
            margin-top: 12px; padding: 10px; }}
QGroupBox::title {{ subcontrol-origin: margin; left: 12px; padding: 0 4px; color: {MUTED}; }}
QScrollArea {{ background: transparent; border: none; }}
QDockWidget {{ titlebar-close-icon: none; color: {MUTED}; }}
QDockWidget::title {{ background: {TOOLBAR}; padding: 8px 12px; border-bottom: 1px solid {BORDER}; }}
QTreeWidget {{ background: {SURFACE}; border: none; outline: none; }}
QTreeWidget::item {{ padding: 5px 4px; border-radius: 6px; }}
QTreeWidget::item:hover {{ background: {HOVER}; }}
QTreeWidget::item:selected {{ background: {SEL}; color: {ACCENT}; }}

QScrollBar:vertical {{ background: transparent; width: 11px; margin: 2px; }}
QScrollBar::handle:vertical {{ background: {SCROLL}; border-radius: 5px; min-height: 28px; }}
QScrollBar::handle:vertical:hover {{ background: {SCROLLH}; }}
QScrollBar:horizontal {{ background: transparent; height: 11px; margin: 2px; }}
QScrollBar::handle:horizontal {{ background: {SCROLL}; border-radius: 5px; min-width: 28px; }}
QScrollBar::add-line, QScrollBar::sub-line {{ width: 0; height: 0; }}
QScrollBar::add-page, QScrollBar::sub-page {{ background: transparent; }}

QToolTip {{ background: {SURFACE}; color: {TEXT}; border: 1px solid {BORDER};
           padding: 4px 8px; border-radius: 6px; }}
QTableWidget {{ background: {SURFACE}; gridline-color: {BORDER}; border: 1px solid {BORDER};
               border-radius: 8px; }}
QHeaderView::section {{ background: {TOOLBAR}; color: {MUTED}; border: none; padding: 6px; }}

#floatResult {{ background: {SURFACE}; border: 1px solid {BORDER}; border-radius: 16px; }}

#homePage {{ background: {BG}; }}
#openCard {{ background: {SURFACE}; border: 1px solid {BORDER}; border-radius: 16px; }}
#openCard:hover {{ border: 1px solid {ACCENT}; background: {HOVER}; }}
#openTitle {{ font-size: 19px; font-weight: 700; color: {TEXT}; }}
#recentTitle {{ font-size: 24px; font-weight: 800; color: {TEXT}; }}
#recentRow {{ background: transparent; border: 1px solid transparent; border-radius: 12px; }}
#recentRow:hover {{ background: {HOVER}; border: 1px solid {BORDER}; }}
#recentName {{ font-size: 15px; color: {TEXT}; }}
#recentDate {{ color: {MUTED}; font-size: 13px; }}
"""

THEMES = {
 "neutral": dict(NAME="Neutral 现代中性", BG="#f5f6f7", SURFACE="#ffffff", TEXT="#2a2d31",
                MUTED="#868b91", ACCENT="#51647d", ACCENT_H="#61748d", ACCENT_P="#41526a",
                ON_ACCENT="#ffffff", BORDER="#e7e9eb", TOOLBAR="#eef0f2", HOVER="#ebedef",
                SEL="#dfe4e9", DISABLED="#e7e9eb", SCROLL="#cdd2d8", SCROLLH="#aab1b9"),
 "cream":  dict(NAME="Cream 浅奶白", BG="#f6f1e6", SURFACE="#fffdf8", TEXT="#5b4d3a",
                MUTED="#9c8b72", ACCENT="#b07d4b", ACCENT_H="#c08a56", ACCENT_P="#956637",
                ON_ACCENT="#fffdf8", BORDER="#e7dcc6", TOOLBAR="#efe7d6", HOVER="#efe6d3",
                SEL="#e3d6ba", DISABLED="#e3d6ba", SCROLL="#d8c8a8", SCROLLH="#c3ad84"),
 "sepia":  dict(NAME="Sepia 深褐护眼", BG="#ecdfc6", SURFACE="#f6ecd6", TEXT="#4a3a28",
                MUTED="#8a7456", ACCENT="#9a6b3c", ACCENT_H="#ac7a48", ACCENT_P="#825733",
                ON_ACCENT="#f6ecd6", BORDER="#d8c39c", TOOLBAR="#e3d3b3", HOVER="#e0cfa9",
                SEL="#d3bd91", DISABLED="#d8c39c", SCROLL="#c7ad81", SCROLLH="#b0925f"),
 "light":  dict(NAME="Light 浅色清爽", BG="#f7f9fc", SURFACE="#ffffff", TEXT="#1f2937",
                MUTED="#6b7280", ACCENT="#2563eb", ACCENT_H="#3b76f0", ACCENT_P="#1d4ed8",
                ON_ACCENT="#ffffff", BORDER="#e5e9f0", TOOLBAR="#eef2f8", HOVER="#eef2fb",
                SEL="#dde6fa", DISABLED="#e5e9f0", SCROLL="#cbd5e1", SCROLLH="#94a3b8"),
 "white":  dict(NAME="White 纯白", BG="#ffffff", SURFACE="#ffffff", TEXT="#18181b",
                MUTED="#71717a", ACCENT="#3f3f46", ACCENT_H="#52525b", ACCENT_P="#27272a",
                ON_ACCENT="#ffffff", BORDER="#e4e4e7", TOOLBAR="#fafafa", HOVER="#f4f4f5",
                SEL="#e4e4e7", DISABLED="#e4e4e7", SCROLL="#d4d4d8", SCROLLH="#a1a1aa"),
 "dark":   dict(NAME="Dark 暗色现代", BG="#14161c", SURFACE="#1c1f27", TEXT="#d7dbe3",
                MUTED="#8b93a3", ACCENT="#6366f1", ACCENT_H="#757af5", ACCENT_P="#4f52d6",
                ON_ACCENT="#ffffff", BORDER="#2a2f3a", TOOLBAR="#191c23", HOVER="#262b36",
                SEL="#313747", DISABLED="#2a2f3a", SCROLL="#3a4150", SCROLLH="#525b6d"),
}

if __name__ == "__main__":
    out = Path(__file__).resolve().parent.parent / "data" / "themes"
    out.mkdir(parents=True, exist_ok=True)
    for key, p in THEMES.items():
        (out / f"{key}.qss").write_text(TEMPLATE.format(**p), encoding="utf-8")
        print("wrote", key)
